#define ENCODER_A_PINS { GP2 } 
#define ENCODER_B_PINS { GP1 }

#define WS2812_DI_PIN GP0
#define RGBLIGHT_LED_COUNT 3

#define I2C_DRIVER I2CD1
#define I2C1_SDA_PIN GP10
#define I2C1_SCL_PIN GP9